version: 2.1

orbs:
  slack: circleci/slack@5.0.0  

jobs:
  build:
    docker:
      - image: circleci/python:3.8  
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv  
            . venv/bin/activate   
            pip install -r requirements.txt  
      - run:
          name: Ejecutar script de manipulación de archivos
          command: |
            echo "Ejecutando script de manipulación de archivos..."
            touch temp_file.txt  
      - run:
          name: Forzar fallo
          command: exit 1  

  notify:
    docker:
      - image: circleci/python:3.8  
    steps:
      - slack/notify:
          event: fail  
          channel: "${DEFAULT_CHANNEL_SLACK}"  

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - notify:
          requires:
            - build  
