version: 2.1

orbs:
  slack: circleci/slack@5.0.0  # Asegúrate de usar la última versión

jobs:
  build:
    docker:
      - image: circleci/python:3.8  
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv  
            . venv/bin/activate   
            pip install -r requirements.txt  
      - run:
          name: Ejecutar script de manipulación de archivos
          command: |
            echo "Ejecutando script de manipulación de archivos..."
            touch temp_file.txt  

  test:
    docker:
      - image: circleci/python:3.8  
    steps:
      - checkout  
      - run:
          name: Ejecutar pruebas con pytest
          command: |
            . venv/bin/activate
            pytest  

  notify:
    docker:
      - image: circleci/python:3.8  
    steps:
      - slack/notify:
          event: fail  
          channel: "${DEFAULT_CHANNEL_SLACK}"  

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - notify:
          requires:
            - test  
