version: 2.1

orbs:
  slack: circleci/slack@4.3.2  # Integración con Slack usando el orb oficial

jobs:
  build:
    docker:
      - image: circleci/python:3.8  
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv  
            . venv/bin/activate   
            pip install -r requirements.txt  
      - run:
          name: Ejecutar script de manipulación de archivos
          command: |
            echo "Ejecutando script de manipulación de archivos..."
            touch temp_file.txt  

  test:
    docker:
      - image: circleci/python:3.8  
    steps:
      - checkout  
      - run:
          name: Ejecutar pruebas con pytest
          command: |
            . venv/bin/activate
            pytest  

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - slack/notify:
          requires:
            - test
          event: fail  # Notificar solo si el job de test falla
          channel: "${DEFAULT_CHANNEL_SLACK}"  # Usar la variable de entorno para el canal
